# Generated by Django 5.1.6 on 2025-02-08 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=50)),
                ('creditos', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('teacher_id', models.ForeignKey(help_text='Profesor que imparte la materia', on_delete=django.db.models.deletion.CASCADE, related_name='materias_impartidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(help_text='Estudiante al que se le asigna la calificación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('student_id', models.ForeignKey(help_text='Estudiante inscrito en la materia', on_delete=django.db.models.deletion.CASCADE, related_name='materias_inscritas', to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academia.subjects')),
            ],
            options={
                'unique_together': {('subject_id', 'student_id')},
            },
        ),
    ]
