# Generated by Django 5.1.6 on 2025-02-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='teacher_id',
            field=models.ForeignKey(default=3, help_text='Profesor que imparte la materia', on_delete=django.db.models.deletion.CASCADE, related_name='Profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student_id',
            field=models.ForeignKey(default=4, help_text='Estudiante inscrito en la materia', on_delete=django.db.models.deletion.CASCADE, related_name='Estudiantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(help_text='Estudiante al que se le asigna la calificación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.subjects')),
            ],
        ),
    ]
