# Generated by Django 5.1.6 on 2025-02-07 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_remove_enrollments_fecha_inscripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='teacher_id',
            field=models.ForeignKey(default=3, help_text='Profesor que imparte la materia', on_delete=django.db.models.deletion.CASCADE, related_name='Profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
