# Generated by Django 5.1.6 on 2025-02-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
